easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'content', type: 'fos_ckeditor' }
                    - { property: 'category' }
        Category:
          class: App\Entity\Category
        User:
          form:
            fields:
                - { property: 'username', type: 'email'  }
                - { property: 'plainPassword', type: 'text' }
                - { property: 'roles', type: 'App\Form\RolesChoiceType' }
                - { property: 'isActive' }
          class: App\Entity\User