fos_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
