version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
        - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.2
    ports:
       - "5601:5601"
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - es-network
    depends_on:
      - elasticsearch

networks:
    es-network:
        driver: bridge

volumes:
  db-volume:
  esdata1: